language: ruby
rvm:
- 2.2
- jruby
before_install:
- openssl aes-256-cbc -K $encrypted_1edaa54ca3ee_key -iv $encrypted_1edaa54ca3ee_iv
  -in deploy-key.enc -out deploy-key -d
- openssl aes-256-cbc -K $encrypted_08b530716fe8_key -iv $encrypted_08b530716fe8_iv
  -in deploy-key.enc -out deploy-key -d
